package constants

var RELATIONSHIP_STATE_DEFAULT = "default"
var RELATIONSHIP_STATE_LIKED = "liked"
var RELATIONSHIP_STATE_DISLIKED = "disliked"
var RELATIONSHIP_STATE_BLOCKED = "blocked"
var RELATIONSHIP_STATE_MATCHED = "matched"

